export default {
  type: 'plain',
  show: true,
  zlevel: 0,
  z: 2,
  left: 'center',
  top: '',
  right: '',
  bottom: '',
  width: '',
  height: '',
  orient: 'horizontal',
  align: 'right',
  textStyle: {
    color: '',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontFamily: 'sans-serif',
    fontSize: 12,
    align: null,
    verticalAlign: null,
    lineHeight: null,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
    padding: 0,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
  },
  padding: [85, 50, 50, 50],
  itemGap: 10,
  itemWidth: 25,
  itemHeight: 14,
  formatter: null,
  selectedMode: true,
  inactiveColor: '',
  backgroundColor: 'transparent',
  borderColor: '',
  borderWidth: 0,
  borderRadius: 0,
  scrollDataIndex: 0,
  pageButtonItemGap: 5,
  pageButtonGap: null,
  pageButtonPosition: 'end',
};
