const createTitleOptions = () => ({
  show: true,
  text: '',
  link: '',
  target: 'blank',
  textStyle: {
    color: '',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontFamily: 'sans-serif',
    fontSize: 18,
    align: null,
    verticalAlign: null,
    lineHeight: null,
    width: null,
    height: null,
    textBorderColor: 'transparent',
    textBorderWidth: 0,
    textShadowColor: 'transparent',
    textShadowBlur: 0,
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  subtext: '',
  sublink: '',
  subtarget: 'blank',
  subtextStyle: {
    color: '',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontFamily: 'sans-serif',
    fontSize: 12,
    align: null,
    verticalAlign: null,
    lineHeight: null,
    width: null,
    height: null,
    textBorderColor: 'transparent',
    textBorderWidth: 0,
    textShadowColor: 'transparent',
    textShadowBlur: 0,
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  padding: [20, 100, 20, 100],
  itemGap: 10,
  zlevel: 0,
  z: 2,
  left: 'center',
  top: 'auto',
  right: 'auto',
  bottom: 'auto',
  backgroundColor: 'transparent',
  borderColor: '',
  borderWidth: 0,
  borderRadius: 0,
  shadowBlur: null,
  shadowColor: null,
  shadowOffsetX: 0,
  shadowOffsetY: 0,
});

export default createTitleOptions;
